# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.15
        environment:          
          MONGO_HOST: localhost
          MONGO_USER: userluiza01
          MONGO_PASS: password123
          MONGO_DB: desafioluiza
          MONGO_PORT: 27017
      - image: bitnami/mongodb:latest
        environment:
          MONGODB_DATABASE: desafioluiza
          MONGODB_PASSWORD: password123
          MONGODB_USERNAME: userluiza01
        command: awk 'END{print $1}' /etc/hosts
        ports:
          - 27017:27017

    working_directory: ~/repo

    steps:
      - checkout
      
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            sudo mkdir -p /data/mongodb
            sudo chmod 777 /data/mongodb -R
            docker run --name mongo -v /data/mongodb:/opt/bitnami/mongodb/conf -e MONGODB_USERNAME=$MONGO_USER -e MONGODB_PASSWORD=$MONGO_PASS -e MONGO_DB=$MONGO_DB -p 27017:27017 bitnami/mongodb:latest
            nose2

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
