# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.15
        environment:          
          MONGO_HOST: 172.27.0.3
          MONGO_USER: luiza
          MONGO_PASS: password123
          MONGO_DB: desafioluiza
          MONGO_PORT: 27017
      - image: bitnami/mongodb:latest
        environment:
          MONGODB_DATABASE: desafioluiza
          MONGODB_PASSWORD: password123
          MONGODB_USERNAME: luiza
        command: awk 'END{print $1}' /etc/hosts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: 
          command: |  
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
            echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell
            mongo -u "luiza" -p "password123" --authenticationDatabase "desafioluiza" --host 172.27.0.1
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nose2

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
